/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'standalone',
  images: {
    domains: ['localhost'],
  },
  env: {
    NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
    NEXT_PUBLIC_AUTH_SERVICE_URL: process.env.NEXT_PUBLIC_AUTH_SERVICE_URL,
    NEXT_PUBLIC_STUDENT_SERVICE_URL: process.env.NEXT_PUBLIC_STUDENT_SERVICE_URL,
    NEXT_PUBLIC_STAFF_SERVICE_URL: process.env.NEXT_PUBLIC_STAFF_SERVICE_URL,
    NEXT_PUBLIC_FEE_SERVICE_URL: process.env.NEXT_PUBLIC_FEE_SERVICE_URL,
    NEXT_PUBLIC_HOMEWORK_SERVICE_URL: process.env.NEXT_PUBLIC_HOMEWORK_SERVICE_URL,
    NEXT_PUBLIC_LIBRARY_SERVICE_URL: process.env.NEXT_PUBLIC_LIBRARY_SERVICE_URL,
    NEXT_PUBLIC_EXAM_SERVICE_URL: process.env.NEXT_PUBLIC_EXAM_SERVICE_URL,
    NEXT_PUBLIC_TIMETABLE_SERVICE_URL: process.env.NEXT_PUBLIC_TIMETABLE_SERVICE_URL,
    NEXT_PUBLIC_ATTENDANCE_SERVICE_URL: process.env.NEXT_PUBLIC_ATTENDANCE_SERVICE_URL,
    NEXT_PUBLIC_TRANSPORT_SERVICE_URL: process.env.NEXT_PUBLIC_TRANSPORT_SERVICE_URL,
    NEXT_PUBLIC_COMMUNICATION_SERVICE_URL: process.env.NEXT_PUBLIC_COMMUNICATION_SERVICE_URL,
    NEXT_PUBLIC_ANALYTICS_SERVICE_URL: process.env.NEXT_PUBLIC_ANALYTICS_SERVICE_URL,
    NEXT_PUBLIC_NOTIFICATION_SERVICE_URL: process.env.NEXT_PUBLIC_NOTIFICATION_SERVICE_URL,
    NEXT_PUBLIC_CONFIG_SERVICE_URL: process.env.NEXT_PUBLIC_CONFIG_SERVICE_URL,
    NEXT_PUBLIC_SUPER_ADMIN_SERVICE_URL: process.env.NEXT_PUBLIC_SUPER_ADMIN_SERVICE_URL,
    NEXT_PUBLIC_AI_SERVICE_URL: process.env.NEXT_PUBLIC_AI_SERVICE_URL,
    NEXT_PUBLIC_AI_ANALYTICS_SERVICE_URL: process.env.NEXT_PUBLIC_AI_ANALYTICS_SERVICE_URL,
  },
}

module.exports = nextConfig 