version: '3.8'

services:
  # Frontend (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://api-gateway:8000
      - NEXT_PUBLIC_APP_NAME=AI SchoolOS
      - NEXT_PUBLIC_APP_VERSION=1.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - ai-schoolos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # API Gateway (Development)
  api-gateway:
    build:
      context: ./backend
      dockerfile: Dockerfile.api-gateway
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    volumes:
      - ./backend/api-gateway:/app/api-gateway
      - ./backend/shared:/app/shared
    networks:
      - ai-schoolos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Auth Service (Development)
  auth-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: auth-service
        SERVICE_PORT: 8001
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - SERVICE_NAME=auth-service
      - SERVICE_PORT=8001
    volumes:
      - ./backend/services/auth-service:/app/services/auth-service
      - ./backend/shared:/app/shared
    networks:
      - ai-schoolos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Student Service (Development)
  student-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: student-service
        SERVICE_PORT: 8002
    ports:
      - "8002:8002"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - SERVICE_NAME=student-service
      - SERVICE_PORT=8002
    volumes:
      - ./backend/services/student-service:/app/services/student-service
      - ./backend/shared:/app/shared
    networks:
      - ai-schoolos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ai-schoolos-network:
    driver: bridge 