version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: ai-schoolos-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - api-gateway
      - auth-service
      - student-service
    networks:
      - ai-schoolos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend (Production)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    container_name: ai-schoolos-frontend
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api-gateway:8000
      - NEXT_PUBLIC_APP_NAME=AI SchoolOS
      - NEXT_PUBLIC_APP_VERSION=1.0.0
    networks:
      - ai-schoolos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # API Gateway (Production)
  api-gateway:
    build:
      context: ./backend
      dockerfile: Dockerfile.api-gateway
    container_name: ai-schoolos-api-gateway
    expose:
      - "8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///./schoolos.db
    networks:
      - ai-schoolos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Auth Service (Production)
  auth-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: auth-service
        SERVICE_PORT: 8001
    container_name: ai-schoolos-auth-service
    expose:
      - "8001"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
      - SERVICE_NAME=auth-service
      - SERVICE_PORT=8001
      - DATABASE_URL=sqlite:///./auth_service.db
    networks:
      - ai-schoolos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Student Service (Production)
  student-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: student-service
        SERVICE_PORT: 8002
    container_name: ai-schoolos-student-service
    expose:
      - "8002"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
      - SERVICE_NAME=student-service
      - SERVICE_PORT=8002
      - DATABASE_URL=sqlite:///./student_service.db
    networks:
      - ai-schoolos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  ai-schoolos-network:
    driver: bridge 