version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: ai-schoolos-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - api-gateway
    networks:
      - ai-schoolos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Application (Production)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.optimized
    container_name: ai-schoolos-frontend
    ports:
      - "3000:3000"
    environment:
      # These will be overridden by .env.production file
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      - NEXT_PUBLIC_AUTH_SERVICE_URL=${NEXT_PUBLIC_AUTH_SERVICE_URL:-http://localhost:8001}
      - NEXT_PUBLIC_STUDENT_SERVICE_URL=${NEXT_PUBLIC_STUDENT_SERVICE_URL:-http://localhost:8002}
      - NEXT_PUBLIC_STAFF_SERVICE_URL=${NEXT_PUBLIC_STAFF_SERVICE_URL:-http://localhost:8003}
      - NEXT_PUBLIC_FEE_SERVICE_URL=${NEXT_PUBLIC_FEE_SERVICE_URL:-http://localhost:8004}
      - NEXT_PUBLIC_HOMEWORK_SERVICE_URL=${NEXT_PUBLIC_HOMEWORK_SERVICE_URL:-http://localhost:8005}
      - NEXT_PUBLIC_LIBRARY_SERVICE_URL=${NEXT_PUBLIC_LIBRARY_SERVICE_URL:-http://localhost:8006}
      - NEXT_PUBLIC_EXAM_SERVICE_URL=${NEXT_PUBLIC_EXAM_SERVICE_URL:-http://localhost:8007}
      - NEXT_PUBLIC_TIMETABLE_SERVICE_URL=${NEXT_PUBLIC_TIMETABLE_SERVICE_URL:-http://localhost:8008}
      - NEXT_PUBLIC_ATTENDANCE_SERVICE_URL=${NEXT_PUBLIC_ATTENDANCE_SERVICE_URL:-http://localhost:8009}
      - NEXT_PUBLIC_TRANSPORT_SERVICE_URL=${NEXT_PUBLIC_TRANSPORT_SERVICE_URL:-http://localhost:8010}
      - NEXT_PUBLIC_COMMUNICATION_SERVICE_URL=${NEXT_PUBLIC_COMMUNICATION_SERVICE_URL:-http://localhost:8011}
      - NEXT_PUBLIC_ANALYTICS_SERVICE_URL=${NEXT_PUBLIC_ANALYTICS_SERVICE_URL:-http://localhost:8012}
      - NEXT_PUBLIC_NOTIFICATION_SERVICE_URL=${NEXT_PUBLIC_NOTIFICATION_SERVICE_URL:-http://localhost:8013}
      - NEXT_PUBLIC_CONFIG_SERVICE_URL=${NEXT_PUBLIC_CONFIG_SERVICE_URL:-http://localhost:8014}
      - NEXT_PUBLIC_SUPER_ADMIN_SERVICE_URL=${NEXT_PUBLIC_SUPER_ADMIN_SERVICE_URL:-http://localhost:8015}
      - NEXT_PUBLIC_AI_SERVICE_URL=${NEXT_PUBLIC_AI_SERVICE_URL:-http://localhost:8016}
      - NEXT_PUBLIC_AI_ANALYTICS_SERVICE_URL=${NEXT_PUBLIC_AI_ANALYTICS_SERVICE_URL:-http://localhost:8017}
      - NODE_ENV=production
    env_file:
      - ./frontend/.env.production
    depends_on:
      - api-gateway
    networks:
      - ai-schoolos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # API Gateway
  api-gateway:
    build:
      context: ./backend
      dockerfile: Dockerfile.api-gateway
    container_name: ai-schoolos-api-gateway
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
      - STUDENT_SERVICE_URL=http://student-service:8002
      - STAFF_SERVICE_URL=http://staff-service:8003
      - FEE_SERVICE_URL=http://fee-service:8004
      - HOMEWORK_SERVICE_URL=http://homework-service:8005
      - LIBRARY_SERVICE_URL=http://library-service:8006
      - EXAM_SERVICE_URL=http://exam-service:8007
      - TIMETABLE_SERVICE_URL=http://timetable-service:8008
      - ATTENDANCE_SERVICE_URL=http://attendance-service:8009
      - TRANSPORT_SERVICE_URL=http://transport-service:8010
      - COMMUNICATION_SERVICE_URL=http://communication-service:8011
      - ANALYTICS_SERVICE_URL=http://analytics-service:8012
      - NOTIFICATION_SERVICE_URL=http://notification-service:8013
      - CONFIG_SERVICE_URL=http://config-service:8014
      - SUPER_ADMIN_SERVICE_URL=http://super-admin-service:8015
      - AI_SERVICE_URL=http://ai-service:8016
      - AI_ANALYTICS_SERVICE_URL=http://ai-analytics-service:8017
    depends_on:
      - auth-service
      - student-service
      - staff-service
    networks:
      - ai-schoolos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Auth Service
  auth-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: auth-service
    container_name: ai-schoolos-auth-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # Student Service
  student-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: student-service
    container_name: ai-schoolos-student-service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # Staff Service
  staff-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: staff-service
    container_name: ai-schoolos-staff-service
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # Infrastructure Services
  postgres:
    image: postgres:15
    container_name: ai-schoolos-postgres
    environment:
      POSTGRES_DB: schoolos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    networks:
      - ai-schoolos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d schoolos"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: ai-schoolos-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai-schoolos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ai-schoolos-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: 