version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: ai-schoolos-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - api-gateway
    networks:
      - ai-schoolos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Application (Production)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.optimized
    container_name: ai-schoolos-frontend
    ports:
      - "3000:3000"
    environment:
      # All services point to nginx proxy on port 80
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:80}
      - NEXT_PUBLIC_AUTH_SERVICE_URL=${NEXT_PUBLIC_AUTH_SERVICE_URL:-http://localhost:80}
      - NEXT_PUBLIC_STUDENT_SERVICE_URL=${NEXT_PUBLIC_STUDENT_SERVICE_URL:-http://localhost:80}
      - NEXT_PUBLIC_STAFF_SERVICE_URL=${NEXT_PUBLIC_STAFF_SERVICE_URL:-http://localhost:80}
      - NEXT_PUBLIC_FEE_SERVICE_URL=${NEXT_PUBLIC_FEE_SERVICE_URL:-http://localhost:80}
      - NEXT_PUBLIC_HOMEWORK_SERVICE_URL=${NEXT_PUBLIC_HOMEWORK_SERVICE_URL:-http://localhost:80}
      - NEXT_PUBLIC_LIBRARY_SERVICE_URL=${NEXT_PUBLIC_LIBRARY_SERVICE_URL:-http://localhost:80}
      - NEXT_PUBLIC_EXAM_SERVICE_URL=${NEXT_PUBLIC_EXAM_SERVICE_URL:-http://localhost:80}
      - NEXT_PUBLIC_TIMETABLE_SERVICE_URL=${NEXT_PUBLIC_TIMETABLE_SERVICE_URL:-http://localhost:80}
      - NEXT_PUBLIC_ATTENDANCE_SERVICE_URL=${NEXT_PUBLIC_ATTENDANCE_SERVICE_URL:-http://localhost:80}
      - NEXT_PUBLIC_TRANSPORT_SERVICE_URL=${NEXT_PUBLIC_TRANSPORT_SERVICE_URL:-http://localhost:80}
      - NEXT_PUBLIC_COMMUNICATION_SERVICE_URL=${NEXT_PUBLIC_COMMUNICATION_SERVICE_URL:-http://localhost:80}
      - NEXT_PUBLIC_ANALYTICS_SERVICE_URL=${NEXT_PUBLIC_ANALYTICS_SERVICE_URL:-http://localhost:80}
      - NEXT_PUBLIC_NOTIFICATION_SERVICE_URL=${NEXT_PUBLIC_NOTIFICATION_SERVICE_URL:-http://localhost:80}
      - NEXT_PUBLIC_CONFIG_SERVICE_URL=${NEXT_PUBLIC_CONFIG_SERVICE_URL:-http://localhost:80}
      - NEXT_PUBLIC_SUPER_ADMIN_SERVICE_URL=${NEXT_PUBLIC_SUPER_ADMIN_SERVICE_URL:-http://localhost:80}
      - NEXT_PUBLIC_AI_SERVICE_URL=${NEXT_PUBLIC_AI_SERVICE_URL:-http://localhost:80}
      - NEXT_PUBLIC_AI_ANALYTICS_SERVICE_URL=${NEXT_PUBLIC_AI_ANALYTICS_SERVICE_URL:-http://localhost:80}
      - NODE_ENV=production
    env_file:
      - ./frontend/.env.production
    depends_on:
      - api-gateway
    networks:
      - ai-schoolos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # API Gateway
  api-gateway:
    build:
      context: ./backend
      dockerfile: Dockerfile.api-gateway
    container_name: ai-schoolos-api-gateway
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
      - STUDENT_SERVICE_URL=http://student-service:8002
      - STAFF_SERVICE_URL=http://staff-service:8003
      - FEE_SERVICE_URL=http://fee-service:8004
      - HOMEWORK_SERVICE_URL=http://homework-service:8005
      - LIBRARY_SERVICE_URL=http://library-service:8006
      - EXAM_SERVICE_URL=http://exam-service:8007
      - TIMETABLE_SERVICE_URL=http://timetable-service:8008
      - ATTENDANCE_SERVICE_URL=http://attendance-service:8009
      - TRANSPORT_SERVICE_URL=http://transport-service:8010
      - COMMUNICATION_SERVICE_URL=http://communication-service:8011
      - ANALYTICS_SERVICE_URL=http://analytics-service:8012
      - NOTIFICATION_SERVICE_URL=http://notification-service:8013
      - CONFIG_SERVICE_URL=http://config-service:8014
      - SUPER_ADMIN_SERVICE_URL=http://super-admin-service:8015
      - AI_SERVICE_URL=http://ai-service:8016
      - AI_ANALYTICS_SERVICE_URL=http://ai-analytics-service:8017
    depends_on:
      - auth-service
      - student-service
      - staff-service
    networks:
      - ai-schoolos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Auth Service
  auth-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: auth-service
    container_name: ai-schoolos-auth-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # Student Service
  student-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: student-service
    container_name: ai-schoolos-student-service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # Staff Service
  staff-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: staff-service
    container_name: ai-schoolos-staff-service
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # Fee Service
  fee-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: fee-service
    container_name: ai-schoolos-fee-service
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # Homework Service
  homework-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: homework-service
    container_name: ai-schoolos-homework-service
    ports:
      - "8005:8005"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # Library Service
  library-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: library-service
    container_name: ai-schoolos-library-service
    ports:
      - "8006:8006"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # Exam Service
  exam-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: exam-service
    container_name: ai-schoolos-exam-service
    ports:
      - "8007:8007"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # Timetable Service
  timetable-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: timetable-service
    container_name: ai-schoolos-timetable-service
    ports:
      - "8008:8008"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # Attendance Service
  attendance-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: attendance-service
    container_name: ai-schoolos-attendance-service
    ports:
      - "8009:8009"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # Transport Service
  transport-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: transport-service
    container_name: ai-schoolos-transport-service
    ports:
      - "8010:8010"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # Communication Service
  communication-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: communication-service
    container_name: ai-schoolos-communication-service
    ports:
      - "8011:8011"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # Analytics Service
  analytics-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: analytics-service
    container_name: ai-schoolos-analytics-service
    ports:
      - "8012:8012"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # Notification Service
  notification-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: notification-service
    container_name: ai-schoolos-notification-service
    ports:
      - "8013:8013"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # Config Service
  config-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: config-service
    container_name: ai-schoolos-config-service
    ports:
      - "8014:8014"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # Super Admin Service
  super-admin-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: super-admin-service
    container_name: ai-schoolos-super-admin-service
    ports:
      - "8015:8015"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # AI Service
  ai-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: ai-service
    container_name: ai-schoolos-ai-service
    ports:
      - "8016:8016"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # AI Analytics Service
  ai-analytics-service:
    build:
      context: ./backend
      dockerfile: Dockerfile.service
      args:
        SERVICE_NAME: ai-analytics-service
    container_name: ai-schoolos-ai-analytics-service
    ports:
      - "8017:8017"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schoolos
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ai-schoolos-network
    restart: unless-stopped

  # Infrastructure Services
  postgres:
    image: postgres:15
    container_name: ai-schoolos-postgres
    environment:
      POSTGRES_DB: schoolos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    networks:
      - ai-schoolos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d schoolos"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: ai-schoolos-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai-schoolos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ai-schoolos-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: 